### ISSUE TITLE
Problem with API calls which use  authenticateWithToken()

### ISSUE THREAD

**Issue by minos314** [uniwue-rz/LoginShibboleth#4] opened 2016-12-29 09:48 UTC
Hi,

I use your Plugin whith shibboleth only, so all informations and permissions are obtained via the header parameters if a user visits piwik. This works fine after some configuration. But if I try to use the API with a auth_token via a script the authentication fails, because the authenticateWithToken() method in LoginShibbolethAuth.php returns an AuthResult::FAILURE.

Therefore I think this line
`$user = $piwikUserModel->getUser($login);`
should be treplaced with this line (as used in the Auth.php form the basic Login plugin)
`$user = $piwikUserModel->getUserByTokenAuth($token);`
In my case this works, is this the right way to do it?

Thanks, Simon

**Comment by Dherlou** [comment] 2023-02-20 12:53
This bug seems to have been fixed in the meantime already, as I cannot reproduce it anymore.
If it is still not working for you, hit me up. :)

**Closed by Dherlou** 2023-02-20 12:53 UTC
Labels: bug
